version: '1.0'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "30090:9090"
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "30091:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana
  
  consul:
    image: consul:1.15.4
    container_name: consul-1
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-1
    ports:
      - "5672:5672"
      - "15672:15672"